"""empty message

Revision ID: 75319e35bc48
Revises: a449f6d19780
Create Date: 2019-03-04 04:57:27.895416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75319e35bc48'
down_revision = 'a449f6d19780'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('password', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'password')
    # ### end Alembic commands ###
